### PR TITLE
feat(model): Resolve diagram-links in descriptions

### PR DESCRIPTION
**Pull request by ewuerger**
## Resolving references to diagrams in descriptions automatically

The `properties.HTMLAttributeProperty` is only ever used for the description of any `GenericElement` or for the text of any `reqif.ReqIFElement`. I.e. when ever a rich-text/HTML attribute is set. In there a reference to a diagram object is now resolved on requesting the attribute, references to non-diagram objects and all other content remains as is.

Example from the test model:
image

Thanks to @Paula-Kli for helping during the implementation.

### CODE REVIEW

**Comment by vik378** [comment]
We should not implement this functionality. This will result in bloated descriptions and also deviates from the original intention of a content author. Please do not merge.

**Comment by ewuerger** [comment]
> I actually started to think that capellambse might not be the right place for this functionality after all. Especially now that I'm seeing how much logic this ends up being, I kinda don't really want to do so much on (what the user sees as) a simple attribute access.

I think so too. The feature that I implemented here actually works fine on the get side (imho), but the set side makes some too specific assumptions which restrict the user in the options on images inside of `HTMLAttributeProperty`s. As you mentioned Inline images which are not meant to be diagrams would break. I could work on distinguishing those... but this feels plain wrong in capellambse. This is behavior which should be defined in a derivative product, if at all.

> We should not implement this functionality. This will result in bloated descriptions and also deviates from the original intention of a content author. Please do not merge.

I guess your comment is directed to the `__set__` part, else I don't agree. Evaluating the idea with regards to Change-Control this would induce a nightmare since now dependencies between diagrams and model-objects from descriptions would be created... by capellambse and not Capella. Not cool. Ready to close this PR when you are @vik378 @Wuestengecko

**Comment by vik378** [comment]
I think get part is flawed too, @ewuerger - as an author, I'd like to mention a diagram, like "see more about the thing in action in Scenario1 and Scenario2" - but I don't want to show those in my description. We are creeping into templating - lets not do it, there is a proper app for that

**Comment by ewuerger** [comment]
With all participants to agree we closed this PR.

**Pull request closed without merging**
