### PR TITLE
Draft: Add hierarchical creation

### PR DESCRIPTION
**Pull request by ewuerger**
Added a testcase for creation of the PhysicalArchitecture layer. During the creation the whole structure information is passed as a dictionary and should be created in one go.

@vik378 mentioned the idea that at first the dict is checked against a minimum viable scheme/skeleton of the ModelElement on which the initial create call is requested.

In a later stage there might be generic name (or requried attribute) generation added.

### CODE REVIEW

**Comment by Wuestengecko** [comment]
> @amolenaar marked this pull request as ready for review 4 hours ago

Why that? As far as I can see, this is not ready (the head commit 54ef7d7 is marked "[WIP]", and almost all the CI is red). Did you mean to push some new commits?

**Comment by amolenaar** [comment]
@Wuestengecko Not sure what happened. I did not intent to change it's status.

**Comment by Wuestengecko** [comment]
@amolenaar no big issue. I'll just change it back then.

**Comment by ewuerger** [comment]
Not aligned with the vision anymore.

**Pull request closed without merging**
